"""initial schema

Revision ID: 0ff6f9394340
Revises: 
Create Date: 2026-02-28 10:15:36.002274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0ff6f9394340'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sites_scraped', sa.Integer(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_matched', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('remote', sa.String(length=50), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_site', sa.String(length=100), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('refined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_jobs_bookmarked', 'jobs', ['is_bookmarked'], unique=False, postgresql_where=sa.text('is_bookmarked = true'))
    op.create_index('idx_jobs_created', 'jobs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_jobs_source', 'jobs', ['source_site'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_source', table_name='jobs')
    op.drop_index('idx_jobs_created', table_name='jobs')
    op.drop_index('idx_jobs_bookmarked', table_name='jobs', postgresql_where=sa.text('is_bookmarked = true'))
    op.drop_table('jobs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
